@WebApplication4_HostAddress = http://localhost:5030

# API: Get short url
# This call should retrun a string "http://localhost:5097/navigate/ge123"
GET {{WebApplication4_HostAddress}}/shortUrls/url1
Accept: application/json

###

# API: Create or update short url
# This call should return a string "http://localhost:5097/navigate/ge123"
PUT {{WebApplication4_HostAddress}}/shortUrls/url1
Accept: application/json
Content-Type: application/json

{
    "url": "http://www.google.com/longurl"
}

###

# API: delete short url
# This call should return empty body
DELETE {{WebApplication4_HostAddress}}/shortUrls/url1
Accept: application/json

###

# API: Get number of hits
# this call should return an integer
GET {{WebApplication4_HostAddress}}/shortUrls/url1/hits
Accept: application/json

###
# API: navigate to shortUrl
# this call should redirect the user to www.google.com
# for how to do that, check https://stackoverflow.com/questions/52308563/redirect-to-url-in-asp-net-core
GET {{WebApplication4_HostAddress}}/navigate/ge123
Accept: application/json